# https://docs.python.org/3/library/logging.html
# https://realpython.com/python-logging/

import logging
import os
from datetime import datetime

LOG_FILE=f"{datetime.now().strftime('%m_%d_%Y_%H_%M_%S')}.log"
logs_path=os.path.join(os.getcwd(),"logs",LOG_FILE)
os.makedirs(logs_path,exist_ok=True)

LOG_FILE_PATH=os.path.join(logs_path,LOG_FILE)

logging.basicConfig(
    filename=LOG_FILE_PATH,
    format="[ %(asctime)s ] %(lineno)d %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)

# to run this file individually and check the logs, use the following code snippet. It will create a log file in the logs folder with the name as the current date and time. The log file will contain the logs generated by the logging module.

# if __name__=="__main__":
#     logging.info("Logging has started")
